### PR TITLE
Update action.yml

### PR DESCRIPTION
**Pull request by Kaibaer**
Changing to use Node20 instead of 16

### CODE REVIEW

**Comment by Kaibaer** [comment]
@YanaXu can you have a look to this? It's the same as in https://github.com/Azure/login/issues/357

**Comment by rwaal** [comment]
I appreciate that the people involved may be very busy. But is there any progress with this PR? Is there anything the community can do to help?

**Comment by YanaXu** [comment]
Thanks to @Kaibaer . I'll close this PR since it's merged by another PR. Thanks for bringing this to us. Sorry for not merging your code. Please try **v2**.

**Comment by YanaXu** [comment]
> I appreciate that the people involved may be very busy. But is there any progress with this PR? Is there anything the community can do to help?

@rwaal , sorry for late response. Please try the new release **v2**.

**Pull request closed without merging**
